/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.assemblyai.api.errors;

import com.assemblyai.api.core.AssemblyAIApiException;
import com.assemblyai.api.types.Error;

public final class TooManyRequestsError extends AssemblyAIApiException {
    /**
     * The body of the response that triggered the exception.
     */
    private final Error body;

    public TooManyRequestsError(Error body) {
        super("TooManyRequestsError", 429, body);
        this.body = body;
    }

    /**
     * @return the body
     */
    @java.lang.Override
    public Error body() {
        return this.body;
    }
}
