/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.assemblyai.api.resources.transcripts.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class EntityType {
    public static final EntityType DRIVERS_LICENSE = new EntityType(Value.DRIVERS_LICENSE, "drivers_license");

    public static final EntityType CREDIT_CARD_CVV = new EntityType(Value.CREDIT_CARD_CVV, "credit_card_cvv");

    public static final EntityType DRUG = new EntityType(Value.DRUG, "drug");

    public static final EntityType PERSON_AGE = new EntityType(Value.PERSON_AGE, "person_age");

    public static final EntityType MONEY_AMOUNT = new EntityType(Value.MONEY_AMOUNT, "money_amount");

    public static final EntityType TIME = new EntityType(Value.TIME, "time");

    public static final EntityType PHONE_NUMBER = new EntityType(Value.PHONE_NUMBER, "phone_number");

    public static final EntityType CREDIT_CARD_EXPIRATION =
            new EntityType(Value.CREDIT_CARD_EXPIRATION, "credit_card_expiration");

    public static final EntityType OCCUPATION = new EntityType(Value.OCCUPATION, "occupation");

    public static final EntityType EVENT = new EntityType(Value.EVENT, "event");

    public static final EntityType LOCATION = new EntityType(Value.LOCATION, "location");

    public static final EntityType URL = new EntityType(Value.URL, "url");

    public static final EntityType LANGUAGE = new EntityType(Value.LANGUAGE, "language");

    public static final EntityType BLOOD_TYPE = new EntityType(Value.BLOOD_TYPE, "blood_type");

    public static final EntityType DATE_OF_BIRTH = new EntityType(Value.DATE_OF_BIRTH, "date_of_birth");

    public static final EntityType PERSON_NAME = new EntityType(Value.PERSON_NAME, "person_name");

    public static final EntityType MEDICAL_PROCESS = new EntityType(Value.MEDICAL_PROCESS, "medical_process");

    public static final EntityType EMAIL_ADDRESS = new EntityType(Value.EMAIL_ADDRESS, "email_address");

    public static final EntityType BANKING_INFORMATION =
            new EntityType(Value.BANKING_INFORMATION, "banking_information");

    public static final EntityType NATIONALITY = new EntityType(Value.NATIONALITY, "nationality");

    public static final EntityType US_SOCIAL_SECURITY_NUMBER =
            new EntityType(Value.US_SOCIAL_SECURITY_NUMBER, "us_social_security_number");

    public static final EntityType INJURY = new EntityType(Value.INJURY, "injury");

    public static final EntityType ORGANIZATION = new EntityType(Value.ORGANIZATION, "organization");

    public static final EntityType POLITICAL_AFFILIATION =
            new EntityType(Value.POLITICAL_AFFILIATION, "political_affiliation");

    public static final EntityType RELIGION = new EntityType(Value.RELIGION, "religion");

    public static final EntityType MEDICAL_CONDITION = new EntityType(Value.MEDICAL_CONDITION, "medical_condition");

    public static final EntityType PASSWORD = new EntityType(Value.PASSWORD, "password");

    public static final EntityType CREDIT_CARD_NUMBER = new EntityType(Value.CREDIT_CARD_NUMBER, "credit_card_number");

    public static final EntityType DATE = new EntityType(Value.DATE, "date");

    private final Value value;

    private final String string;

    EntityType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @Override
    public boolean equals(Object other) {
        return (this == other) || (other instanceof EntityType && this.string.equals(((EntityType) other).string));
    }

    @Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case DRIVERS_LICENSE:
                return visitor.visitDriversLicense();
            case CREDIT_CARD_CVV:
                return visitor.visitCreditCardCvv();
            case DRUG:
                return visitor.visitDrug();
            case PERSON_AGE:
                return visitor.visitPersonAge();
            case MONEY_AMOUNT:
                return visitor.visitMoneyAmount();
            case TIME:
                return visitor.visitTime();
            case PHONE_NUMBER:
                return visitor.visitPhoneNumber();
            case CREDIT_CARD_EXPIRATION:
                return visitor.visitCreditCardExpiration();
            case OCCUPATION:
                return visitor.visitOccupation();
            case EVENT:
                return visitor.visitEvent();
            case LOCATION:
                return visitor.visitLocation();
            case URL:
                return visitor.visitURL();
            case LANGUAGE:
                return visitor.visitLanguage();
            case BLOOD_TYPE:
                return visitor.visitBloodType();
            case DATE_OF_BIRTH:
                return visitor.visitDateOfBirth();
            case PERSON_NAME:
                return visitor.visitPersonName();
            case MEDICAL_PROCESS:
                return visitor.visitMedicalProcess();
            case EMAIL_ADDRESS:
                return visitor.visitEmailAddress();
            case BANKING_INFORMATION:
                return visitor.visitBankingInformation();
            case NATIONALITY:
                return visitor.visitNationality();
            case US_SOCIAL_SECURITY_NUMBER:
                return visitor.visitUsSocialSecurityNumber();
            case INJURY:
                return visitor.visitInjury();
            case ORGANIZATION:
                return visitor.visitOrganization();
            case POLITICAL_AFFILIATION:
                return visitor.visitPoliticalAffiliation();
            case RELIGION:
                return visitor.visitReligion();
            case MEDICAL_CONDITION:
                return visitor.visitMedicalCondition();
            case PASSWORD:
                return visitor.visitPassword();
            case CREDIT_CARD_NUMBER:
                return visitor.visitCreditCardNumber();
            case DATE:
                return visitor.visitDate();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static EntityType valueOf(String value) {
        switch (value) {
            case "drivers_license":
                return DRIVERS_LICENSE;
            case "credit_card_cvv":
                return CREDIT_CARD_CVV;
            case "drug":
                return DRUG;
            case "person_age":
                return PERSON_AGE;
            case "money_amount":
                return MONEY_AMOUNT;
            case "time":
                return TIME;
            case "phone_number":
                return PHONE_NUMBER;
            case "credit_card_expiration":
                return CREDIT_CARD_EXPIRATION;
            case "occupation":
                return OCCUPATION;
            case "event":
                return EVENT;
            case "location":
                return LOCATION;
            case "url":
                return URL;
            case "language":
                return LANGUAGE;
            case "blood_type":
                return BLOOD_TYPE;
            case "date_of_birth":
                return DATE_OF_BIRTH;
            case "person_name":
                return PERSON_NAME;
            case "medical_process":
                return MEDICAL_PROCESS;
            case "email_address":
                return EMAIL_ADDRESS;
            case "banking_information":
                return BANKING_INFORMATION;
            case "nationality":
                return NATIONALITY;
            case "us_social_security_number":
                return US_SOCIAL_SECURITY_NUMBER;
            case "injury":
                return INJURY;
            case "organization":
                return ORGANIZATION;
            case "political_affiliation":
                return POLITICAL_AFFILIATION;
            case "religion":
                return RELIGION;
            case "medical_condition":
                return MEDICAL_CONDITION;
            case "password":
                return PASSWORD;
            case "credit_card_number":
                return CREDIT_CARD_NUMBER;
            case "date":
                return DATE;
            default:
                return new EntityType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        BANKING_INFORMATION,

        BLOOD_TYPE,

        CREDIT_CARD_CVV,

        CREDIT_CARD_EXPIRATION,

        CREDIT_CARD_NUMBER,

        DATE,

        DATE_OF_BIRTH,

        DRIVERS_LICENSE,

        DRUG,

        EMAIL_ADDRESS,

        EVENT,

        INJURY,

        LANGUAGE,

        LOCATION,

        MEDICAL_CONDITION,

        MEDICAL_PROCESS,

        MONEY_AMOUNT,

        NATIONALITY,

        OCCUPATION,

        ORGANIZATION,

        PASSWORD,

        PERSON_AGE,

        PERSON_NAME,

        PHONE_NUMBER,

        POLITICAL_AFFILIATION,

        RELIGION,

        TIME,

        URL,

        US_SOCIAL_SECURITY_NUMBER,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitBankingInformation();

        T visitBloodType();

        T visitCreditCardCvv();

        T visitCreditCardExpiration();

        T visitCreditCardNumber();

        T visitDate();

        T visitDateOfBirth();

        T visitDriversLicense();

        T visitDrug();

        T visitEmailAddress();

        T visitEvent();

        T visitInjury();

        T visitLanguage();

        T visitLocation();

        T visitMedicalCondition();

        T visitMedicalProcess();

        T visitMoneyAmount();

        T visitNationality();

        T visitOccupation();

        T visitOrganization();

        T visitPassword();

        T visitPersonAge();

        T visitPersonName();

        T visitPhoneNumber();

        T visitPoliticalAffiliation();

        T visitReligion();

        T visitTime();

        T visitURL();

        T visitUsSocialSecurityNumber();

        T visitUnknown(String unknownType);
    }
}
