/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.assemblyai.api.resources.transcripts.types;

import com.assemblyai.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TranscriptSentence.Builder.class)
public final class TranscriptSentence {
    private final String text;

    private final int start;

    private final int end;

    private final double confidence;

    private final List<TranscriptWord> words;

    private final Optional<String> channel;

    private final Optional<String> speaker;

    private final Map<String, Object> additionalProperties;

    private TranscriptSentence(
            String text,
            int start,
            int end,
            double confidence,
            List<TranscriptWord> words,
            Optional<String> channel,
            Optional<String> speaker,
            Map<String, Object> additionalProperties) {
        this.text = text;
        this.start = start;
        this.end = end;
        this.confidence = confidence;
        this.words = words;
        this.channel = channel;
        this.speaker = speaker;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The transcript of the sentence
     */
    @JsonProperty("text")
    public String getText() {
        return text;
    }

    /**
     * @return The starting time, in milliseconds, for the sentence
     */
    @JsonProperty("start")
    public int getStart() {
        return start;
    }

    /**
     * @return The ending time, in milliseconds, for the sentence
     */
    @JsonProperty("end")
    public int getEnd() {
        return end;
    }

    /**
     * @return The confidence score for the transcript of this sentence
     */
    @JsonProperty("confidence")
    public double getConfidence() {
        return confidence;
    }

    /**
     * @return An array of words in the sentence
     */
    @JsonProperty("words")
    public List<TranscriptWord> getWords() {
        return words;
    }

    /**
     * @return The channel of the sentence. The left and right channels are channels 1 and 2. Additional channels increment the channel number sequentially.
     */
    @JsonProperty("channel")
    public Optional<String> getChannel() {
        return channel;
    }

    /**
     * @return The speaker of the sentence if <a href="https://www.assemblyai.com/docs/models/speaker-diarization">Speaker Diarization</a> is enabled, else null
     */
    @JsonProperty("speaker")
    public Optional<String> getSpeaker() {
        return speaker;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TranscriptSentence && equalTo((TranscriptSentence) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TranscriptSentence other) {
        return text.equals(other.text)
                && start == other.start
                && end == other.end
                && confidence == other.confidence
                && words.equals(other.words)
                && channel.equals(other.channel)
                && speaker.equals(other.speaker);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.text, this.start, this.end, this.confidence, this.words, this.channel, this.speaker);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TextStage builder() {
        return new Builder();
    }

    public interface TextStage {
        StartStage text(String text);

        Builder from(TranscriptSentence other);
    }

    public interface StartStage {
        EndStage start(int start);
    }

    public interface EndStage {
        ConfidenceStage end(int end);
    }

    public interface ConfidenceStage {
        _FinalStage confidence(double confidence);
    }

    public interface _FinalStage {
        TranscriptSentence build();

        _FinalStage words(List<TranscriptWord> words);

        _FinalStage addWords(TranscriptWord words);

        _FinalStage addAllWords(List<TranscriptWord> words);

        _FinalStage channel(Optional<String> channel);

        _FinalStage channel(String channel);

        _FinalStage speaker(Optional<String> speaker);

        _FinalStage speaker(String speaker);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TextStage, StartStage, EndStage, ConfidenceStage, _FinalStage {
        private String text;

        private int start;

        private int end;

        private double confidence;

        private Optional<String> speaker = Optional.empty();

        private Optional<String> channel = Optional.empty();

        private List<TranscriptWord> words = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(TranscriptSentence other) {
            text(other.getText());
            start(other.getStart());
            end(other.getEnd());
            confidence(other.getConfidence());
            words(other.getWords());
            channel(other.getChannel());
            speaker(other.getSpeaker());
            return this;
        }

        /**
         * <p>The transcript of the sentence</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("text")
        public StartStage text(String text) {
            this.text = text;
            return this;
        }

        /**
         * <p>The starting time, in milliseconds, for the sentence</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("start")
        public EndStage start(int start) {
            this.start = start;
            return this;
        }

        /**
         * <p>The ending time, in milliseconds, for the sentence</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("end")
        public ConfidenceStage end(int end) {
            this.end = end;
            return this;
        }

        /**
         * <p>The confidence score for the transcript of this sentence</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("confidence")
        public _FinalStage confidence(double confidence) {
            this.confidence = confidence;
            return this;
        }

        /**
         * <p>The speaker of the sentence if <a href="https://www.assemblyai.com/docs/models/speaker-diarization">Speaker Diarization</a> is enabled, else null</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage speaker(String speaker) {
            this.speaker = Optional.ofNullable(speaker);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "speaker", nulls = Nulls.SKIP)
        public _FinalStage speaker(Optional<String> speaker) {
            this.speaker = speaker;
            return this;
        }

        /**
         * <p>The channel of the sentence. The left and right channels are channels 1 and 2. Additional channels increment the channel number sequentially.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage channel(String channel) {
            this.channel = Optional.ofNullable(channel);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "channel", nulls = Nulls.SKIP)
        public _FinalStage channel(Optional<String> channel) {
            this.channel = channel;
            return this;
        }

        /**
         * <p>An array of words in the sentence</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllWords(List<TranscriptWord> words) {
            this.words.addAll(words);
            return this;
        }

        /**
         * <p>An array of words in the sentence</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addWords(TranscriptWord words) {
            this.words.add(words);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "words", nulls = Nulls.SKIP)
        public _FinalStage words(List<TranscriptWord> words) {
            this.words.clear();
            this.words.addAll(words);
            return this;
        }

        @java.lang.Override
        public TranscriptSentence build() {
            return new TranscriptSentence(text, start, end, confidence, words, channel, speaker, additionalProperties);
        }
    }
}
