/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.assemblyai.api.types;

import java.util.List;
import java.util.Optional;

public interface ILemurBaseParameters {
    List<String> getTranscriptIds();

    Optional<LemurBaseParametersContext> getContext();

    Optional<LemurModels> getFinalModel();

    Optional<Integer> getMaxOutputSize();

    Optional<Double> getTemperature();
}
