/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.assemblyai.api.types;

import java.util.List;
import java.util.Optional;

public interface ILemurBaseParameters {
    Optional<List<String>> getTranscriptIds();

    Optional<String> getInputText();

    Optional<LemurBaseParametersContext> getContext();

    Optional<LemurModel> getFinalModel();

    Optional<Integer> getMaxOutputSize();

    Optional<Double> getTemperature();
}
