package com.assemblyai.api.types;

import com.assemblyai.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = LemurQuestionAnswerResults.Builder.class)
public final class LemurQuestionAnswerResults {
    private final Optional<String> requestId;

    private final Optional<List<LemurQuestionAnswer>> response;

    private LemurQuestionAnswerResults(Optional<String> requestId, Optional<List<LemurQuestionAnswer>> response) {
        this.requestId = requestId;
        this.response = response;
    }

    /**
     * @return The ID of the LeMUR request
     */
    @JsonProperty("request_id")
    public Optional<String> getRequestId() {
        return requestId;
    }

    /**
     * @return The answers generated by LeMUR and their questions.
     */
    @JsonProperty("response")
    public Optional<List<LemurQuestionAnswer>> getResponse() {
        return response;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof LemurQuestionAnswerResults && equalTo((LemurQuestionAnswerResults) other);
    }

    private boolean equalTo(LemurQuestionAnswerResults other) {
        return requestId.equals(other.requestId) && response.equals(other.response);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.requestId, this.response);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> requestId = Optional.empty();

        private Optional<List<LemurQuestionAnswer>> response = Optional.empty();

        private Builder() {}

        public Builder from(LemurQuestionAnswerResults other) {
            requestId(other.getRequestId());
            response(other.getResponse());
            return this;
        }

        @JsonSetter(value = "request_id", nulls = Nulls.SKIP)
        public Builder requestId(Optional<String> requestId) {
            this.requestId = requestId;
            return this;
        }

        public Builder requestId(String requestId) {
            this.requestId = Optional.of(requestId);
            return this;
        }

        @JsonSetter(value = "response", nulls = Nulls.SKIP)
        public Builder response(Optional<List<LemurQuestionAnswer>> response) {
            this.response = response;
            return this;
        }

        public Builder response(List<LemurQuestionAnswer> response) {
            this.response = Optional.of(response);
            return this;
        }

        public LemurQuestionAnswerResults build() {
            return new LemurQuestionAnswerResults(requestId, response);
        }
    }
}
