package com.assemblyai.api.types;

import com.assemblyai.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = LemurQuestionAnswerResults.Builder.class)
public final class LemurQuestionAnswerResults {
    private final String requestId;

    private final List<LemurQuestionAnswer> response;

    private LemurQuestionAnswerResults(String requestId, List<LemurQuestionAnswer> response) {
        this.requestId = requestId;
        this.response = response;
    }

    /**
     * @return The ID of the LeMUR request
     */
    @JsonProperty("request_id")
    public String getRequestId() {
        return requestId;
    }

    /**
     * @return The answers generated by LeMUR and their questions.
     */
    @JsonProperty("response")
    public List<LemurQuestionAnswer> getResponse() {
        return response;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof LemurQuestionAnswerResults && equalTo((LemurQuestionAnswerResults) other);
    }

    private boolean equalTo(LemurQuestionAnswerResults other) {
        return requestId.equals(other.requestId) && response.equals(other.response);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.requestId, this.response);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static RequestIdStage builder() {
        return new Builder();
    }

    public interface RequestIdStage {
        _FinalStage requestId(String requestId);

        Builder from(LemurQuestionAnswerResults other);
    }

    public interface _FinalStage {
        LemurQuestionAnswerResults build();

        _FinalStage response(List<LemurQuestionAnswer> response);

        _FinalStage addResponse(LemurQuestionAnswer response);

        _FinalStage addAllResponse(List<LemurQuestionAnswer> response);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements RequestIdStage, _FinalStage {
        private String requestId;

        private List<LemurQuestionAnswer> response = new ArrayList<>();

        private Builder() {}

        @Override
        public Builder from(LemurQuestionAnswerResults other) {
            requestId(other.getRequestId());
            response(other.getResponse());
            return this;
        }

        /**
         * <p>The ID of the LeMUR request</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        @JsonSetter("request_id")
        public _FinalStage requestId(String requestId) {
            this.requestId = requestId;
            return this;
        }

        /**
         * <p>The answers generated by LeMUR and their questions.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        public _FinalStage addAllResponse(List<LemurQuestionAnswer> response) {
            this.response.addAll(response);
            return this;
        }

        /**
         * <p>The answers generated by LeMUR and their questions.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        public _FinalStage addResponse(LemurQuestionAnswer response) {
            this.response.add(response);
            return this;
        }

        @Override
        @JsonSetter(value = "response", nulls = Nulls.SKIP)
        public _FinalStage response(List<LemurQuestionAnswer> response) {
            this.response.clear();
            this.response.addAll(response);
            return this;
        }

        @Override
        public LemurQuestionAnswerResults build() {
            return new LemurQuestionAnswerResults(requestId, response);
        }
    }
}
