/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.assemblyai.api.types;

import com.assemblyai.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = RealtimeError.Builder.class)
public final class RealtimeError {
    private final String error;

    private RealtimeError(String error) {
        this.error = error;
    }

    @JsonProperty("error")
    public String getError() {
        return error;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof RealtimeError && equalTo((RealtimeError) other);
    }

    private boolean equalTo(RealtimeError other) {
        return error.equals(other.error);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.error);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ErrorStage builder() {
        return new Builder();
    }

    public interface ErrorStage {
        _FinalStage error(String error);

        Builder from(RealtimeError other);
    }

    public interface _FinalStage {
        RealtimeError build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ErrorStage, _FinalStage {
        private String error;

        private Builder() {}

        @Override
        public Builder from(RealtimeError other) {
            error(other.getError());
            return this;
        }

        @Override
        @JsonSetter("error")
        public _FinalStage error(String error) {
            this.error = error;
            return this;
        }

        @Override
        public RealtimeError build() {
            return new RealtimeError(error);
        }
    }
}
