/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.assemblyai.api.types;

import com.assemblyai.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = RealtimeTokenResponseBody.Builder.class)
public final class RealtimeTokenResponseBody {
    private final String token;

    private RealtimeTokenResponseBody(String token) {
        this.token = token;
    }

    /**
     * @return The temporary authentication token for realtime transcription
     */
    @JsonProperty("token")
    public String getToken() {
        return token;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof RealtimeTokenResponseBody && equalTo((RealtimeTokenResponseBody) other);
    }

    private boolean equalTo(RealtimeTokenResponseBody other) {
        return token.equals(other.token);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.token);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TokenStage builder() {
        return new Builder();
    }

    public interface TokenStage {
        _FinalStage token(String token);

        Builder from(RealtimeTokenResponseBody other);
    }

    public interface _FinalStage {
        RealtimeTokenResponseBody build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TokenStage, _FinalStage {
        private String token;

        private Builder() {}

        @Override
        public Builder from(RealtimeTokenResponseBody other) {
            token(other.getToken());
            return this;
        }

        /**
         * <p>The temporary authentication token for realtime transcription</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        @JsonSetter("token")
        public _FinalStage token(String token) {
            this.token = token;
            return this;
        }

        @Override
        public RealtimeTokenResponseBody build() {
            return new RealtimeTokenResponseBody(token);
        }
    }
}
