/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.assemblyai.api.types;

import com.assemblyai.api.core.ObjectMappers;

public final class SessionTerminated {
    private SessionTerminated() {}

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SessionTerminated;
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }
}
